defaults:
  - default_train_params

max_epochs: 100

average_best_models: True

# lr_cooldown_epochs: 15

warmup_mode: "linear_epoch_step"
warmup_initial_lr:  1.e-6
lr_warmup_epochs: 5

initial_lr:  1.e-2
lr_mode: cosine
cosine_final_lr_ratio: 0.01

zero_weight_decay_on_bias_and_bn: True
batch_accumulate: 1

# save_ckpt_epoch_list: [100, 200, 250]

loss:
  ppyoloe_loss:
    use_static_assigner: False
    num_classes: ${arch_params.num_classes}
    reg_max: 16

optimizer: Adam
optimizer_params:
  weight_decay: 0.0001

ema: True
ema_params:
  decay: 0.9
  decay_type: threshold

mixed_precision: True
# sync_bn: True

valid_metrics_list:
  - DetectionMetrics_050:
      score_thres: 0.1
      top_k_predictions: 300
      num_cls: ${arch_params.num_classes}
      normalize_targets: True
      post_prediction_callback:
        _target_: super_gradients.training.models.detection_models.pp_yolo_e.PPYoloEPostPredictionCallback
        score_threshold: 0.3
        nms_top_k: 200
        max_predictions: 20
        nms_threshold: 0.5

pre_prediction_callback:

metric_to_watch: 'mAP@0.50'
greater_metric_to_watch_is_better: True

_convert_: all
