defaults:
  - default_train_params

max_epochs: 100

warmup_mode: "linear_epoch_step"
warmup_initial_lr:  1.e-8
lr_warmup_epochs: 5

initial_lr:  5.e-4
lr_mode: cosine
cosine_final_lr_ratio: 0.1

lr_cooldown_epochs: 15

zero_weight_decay_on_bias_and_bn: True
batch_accumulate: 1

# save_ckpt_epoch_list: [285]

loss: yolox_loss

criterion_params:
  strides: [8, 16, 32]  # output strides of all yolo outputs
  num_classes: ${arch_params.num_classes}

optimizer: AdamW
optimizer_params:
  weight_decay: 0.0005
# optimizer: SGD
# optimizer_params:
#   momentum: 0.9
#   weight_decay: 0.0005
#   nesterov: True

ema: True
ema_params:
  decay: 0.9997
  decay_type: threshold

mixed_precision: True
sync_bn: True

valid_metrics_list:
  - DetectionMetrics:
      score_thres: 0.5
      top_k_predictions: 300
      num_cls: ${arch_params.num_classes}
      normalize_targets: True
      post_prediction_callback:
        _target_: super_gradients.training.models.detection_models.yolo_base.YoloPostPredictionCallback
        iou: 0.5
        conf: 0.8
  - DetectionMetrics_050:
      score_thres: 0.5
      top_k_predictions: 300
      num_cls: ${arch_params.num_classes}
      normalize_targets: True
      post_prediction_callback:
        _target_: super_gradients.training.models.detection_models.yolo_base.YoloPostPredictionCallback
        iou: 0.5
        conf: 0.8

pre_prediction_callback:

# phase_callbacks:
#   - YoloXTrainingStageSwitchCallback:
#       next_stage_start_epoch: 285

metric_to_watch: 'mAP@0.50:0.95'
greater_metric_to_watch_is_better: True

_convert_: all
