# YoloNAS-S Detection training on COCO2017 Dataset:
# This training recipe is for demonstration purposes only. Pretrained models were trained using a different recipe.
# So it will not be possible to reproduce the results of the pretrained models using this recipe.

# Instructions:
#   0. Make sure that the data is stored in dataset_params.dataset_dir or add "dataset_params.data_dir=<PATH-TO-DATASET>" at the end of the command below (feel free to check ReadMe)
#   1. Move to the project root (where you will find the ReadMe and src folder)
#   2. Run the command you want:
#         yolo_nas_s: python src/super_gradients/examples/train_from_recipe_example/train_from_recipe.py --config-name=coco2017_yolo_nas_s
#

defaults:
  - training_hyperparams: a3_yolo_nas_train_params
  - dataset_params: a3_detection_yolo_nas_dataset_params
  - arch_params: yolo_nas_s_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

train_dataloader: coco_detection_yolo_format_train
val_dataloader: coco_detection_yolo_format_val

dataset_params:
  train_dataloader_params:
    batch_size: 6
  val_dataloader_params:
    batch_size: 6

num_classes: 1

architecture: yolo_nas_s
arch_params:
  num_classes: ${num_classes}

load_checkpoint: False
checkpoint_params:
  pretrained_weights: coco

result_path: # By defaults saves results in checkpoints directory

resume: False
training_hyperparams:
  resume: ${resume}

multi_gpu: DDP
num_gpus: 8

experiment_suffix: "baseline"
experiment_name: ${architecture}_a3_${experiment_suffix}
