defaults:
  - training_hyperparams: lard_yolo_nas_train_params
  - dataset_params: lard_detection_yolo_nas_dataset_params
  - arch_params: yolo_nas_s_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

train_dataloader: coco_detection_yolo_format_train
val_dataloader: coco_detection_yolo_format_val

dataset_params:
  train_dataloader_params:
    batch_size: 6
  val_dataloader_params:
    batch_size: 6

num_classes: 1

architecture: yolo_nas_s
arch_params:
  num_classes: ${num_classes}

load_checkpoint: False
checkpoint_params:
  pretrained_weights: coco

result_path: # By defaults saves results in checkpoints directory

resume: False
training_hyperparams:
  resume: ${resume}

multi_gpu: DDP
num_gpus: 8

experiment_suffix: "baseline"
experiment_name: ${architecture}_lard_${experiment_suffix}
